In [1]:
pip install netcdf4 wget

     |████████████████████████████████| 4.7MB 11.2MB/s 
     |████████████████████████████████| 317kB 60.0MB/s 
  Created wheel for wget: filename=wget-3.2-cp37-none-any.whl size=9681 sha256=148dc5fb16829ee6108f9a86c1791eb79eaf91214770f7ea1ece42c7d1dceea1
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [2]:
import pandas as pd
import netCDF4
import numpy as np
import datetime
import time
from google.colab import files
import wget
import os

In [3]:
wget.download('http://dapds00.nci.org.au/thredds/fileServer/ub8/au/FMC/c6/fmc_c6_2021_h27v12.nc')

'fmc_c6_2021_h27v12.nc'

In [4]:
nc = netCDF4.Dataset('fmc_c6_2021_h27v12.nc', mode='r')

In [5]:
#nc.dimensions

In [6]:
#nc.variables

In [7]:
#nc.ncattrs()

In [8]:
#print(nc)

In [70]:
time_var = nc.variables['time'][:].filled()

In [79]:
time_var.size-1

27

In [71]:
dtime = netCDF4.num2date(time_var[:], 'seconds since 1970-01-01 00:00:00.0')

In [72]:
dtime

array([cftime.DatetimeGregorian(2021, 1, 1, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 5, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 9, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 13, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 17, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 21, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 25, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 1, 29, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 2, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 6, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 10, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 14, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 18, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 22, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 2, 26, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 3, 2, 0, 0, 0, 0),
       cftime.DatetimeGregorian(2021, 3, 6, 0, 0, 0, 0),
       cftime.Datetim

In [73]:
time_var

array([1.6094592e+09, 1.6098048e+09, 1.6101504e+09, 1.6104960e+09,
       1.6108416e+09, 1.6111872e+09, 1.6115328e+09, 1.6118784e+09,
       1.6122240e+09, 1.6125696e+09, 1.6129152e+09, 1.6132608e+09,
       1.6136064e+09, 1.6139520e+09, 1.6142976e+09, 1.6146432e+09,
       1.6149888e+09, 1.6153344e+09, 1.6156800e+09, 1.6160256e+09,
       1.6163712e+09, 1.6167168e+09, 1.6170624e+09, 1.6174080e+09,
       1.6177536e+09, 1.6180992e+09, 1.6184448e+09, 1.6187904e+09])

In [74]:
dtime.size-1

27

In [75]:
dtime[dtime.size-1].strftime('%Y%m%d')

'20210419'

In [76]:
lfmc_mean = nc.variables['lfmc_mean'][dtime.size-1][:][:].filled()
lfmc_stdv = nc.variables['lfmc_stdv'][dtime.size-1][:][:].filled()

In [77]:
lfmc_mean

array([[-9.99990e+03, -9.99990e+03, -9.99990e+03, ...,  1.31325e+01,
         9.06500e+00,  7.75500e+00],
       [-9.99990e+03, -9.99990e+03, -9.99990e+03, ...,  2.74150e+01,
         3.34075e+01,  5.56625e+01],
       [-9.99990e+03, -9.99990e+03, -9.99990e+03, ...,  1.45175e+01,
         5.56625e+01,  5.56625e+01],
       ...,
       [-9.99990e+03, -9.99990e+03, -9.99990e+03, ..., -9.99990e+03,
        -9.99990e+03, -9.99990e+03],
       [-9.99990e+03, -9.99990e+03, -9.99990e+03, ..., -9.99990e+03,
        -9.99990e+03, -9.99990e+03],
       [-9.99990e+03, -9.99990e+03, -9.99990e+03, ..., -9.99990e+03,
        -9.99990e+03, -9.99990e+03]], dtype=float32)

In [16]:
wget.download('https://calwildfire.thesofttools.com/h27v12_lat_lon_ref.nc')

'h27v12_lat_lon_ref.nc'

In [43]:
ll = netCDF4.Dataset('h27v12_lat_lon_ref.nc', mode='r')
lat = ll.variables['lat'][:][:].filled()
lon = ll.variables['lon'][:][:].filled()

In [44]:
lat.size

5760000

In [46]:
lat

array([[-30.00103879, -30.00103879, -30.00103879, ..., -30.00103879,
        -30.00103879, -30.00103879],
       [-30.00520531, -30.00520531, -30.00520531, ..., -30.00520531,
        -30.00520531, -30.00520531],
       [-30.00937183, -30.00937183, -30.00937183, ..., -30.00937183,
        -30.00937183, -30.00937183],
       ...,
       [-39.98819106, -39.98819106, -39.98819106, ..., -39.98819106,
        -39.98819106, -39.98819106],
       [-39.99235758, -39.99235758, -39.99235758, ..., -39.99235758,
        -39.99235758, -39.99235758],
       [-39.99652411, -39.99652411, -39.99652411, ..., -39.99652411,
        -39.99652411, -39.99652411]])

In [19]:
np.savez_compressed('lat_h27v12.npz', lat=lat, lon=lon)

In [35]:
lfmc_mean.size

5760000

In [53]:
np.savez_compressed('lfmc_h27v12.npz', mean=lfmc_mean, stdv=lfmc_stdv)

In [54]:
!ls -latrh

total 1.6G
drwxr-xr-x 4 root root 4.0K Apr 21 13:38 .config
drwxr-xr-x 1 root root 4.0K Apr 21 13:39 sample_data
drwxr-xr-x 1 root root 4.0K May  2 05:09 ..
-rw-r--r-- 1 root root 1.4G May  2 05:14 fmc_c6_2021_h27v12.nc
-rw-r--r-- 1 root root 132M May  2 05:14 h27v12_lat_lon_ref.nc
-rw-r--r-- 1 root root  35M May  2 05:14 lat_h27v12.npz
drwxr-xr-x 1 root root 4.0K May  2 05:14 .
-rw-r--r-- 1 root root 3.6M May  2 05:46 lfmc_h27v12.npz


In [23]:
loaded = np.load('lfmc_h27v12.npz')

In [24]:
loaded['mean'].size

5760000

In [25]:
loaded['stdv'].size

5760000

In [26]:
print("%d mega bytes" % (loaded['mean'].size * loaded['mean'].itemsize/1024/1024))

21 mega bytes


In [27]:
print("%d mega bytes" % (loaded['stdv'].size * loaded['stdv'].itemsize/1024/1024))

21 mega bytes


In [28]:
print("%d mega bytes" % (lat.size * lat.itemsize/1024/1024))

43 mega bytes


In [29]:
print("%d mega bytes" % (lon.size * lon.itemsize/1024/1024))

43 mega bytes


In [30]:
x=np.load('lat_h27v12.npz')

In [31]:
print("%d mega bytes" % (x['lon'].size * x['lon'].itemsize/1024/1024))

43 mega bytes


In [47]:
diff = abs(lat - (-32.0794)) + abs(lon - 116.0867)

In [48]:
diff

array([[14.24213755, 14.23732642, 14.23251528, ...,  2.70984673,
         2.70503559,  2.70022446],
       [14.23360723, 14.22879589, 14.22398455, ...,  2.70083215,
         2.69602081,  2.69120947],
       [14.22507598, 14.22026444, 14.2154529 , ...,  2.69181655,
         2.68700501,  2.68219347],
       ...,
       [ 9.28706402,  9.29250209,  9.29794016, ..., 22.32211137,
        22.32754944, 22.3329875 ],
       [ 9.29839588,  9.30383428,  9.30927268, ..., 22.33423836,
        22.33967676, 22.34511516],
       [ 9.30972923,  9.31516796,  9.32060669, ..., 22.34636701,
        22.35180574, 22.35724447]])

In [65]:
np.unravel_index(diff.argmin(), diff.shape)

(499, 2007)

In [61]:
diff[499][2007]

0.0009528621262120396

In [66]:
diff[499][2007]=99999

In [67]:
np.unravel_index(diff.argmin(), diff.shape)

(498, 2008)

In [68]:
lat[498][2008]

-32.07596654332369

In [69]:
lon[498][2008]

116.08654605199953

In [78]:
lfmc_mean[498][2008]

110.0